//! Passphrase generation (Crockford base32 from the OS CSPRNG, generated by
//! default) and the 12-character floor applied to a user-supplied one, with the
//! offline-attack cost explained rather than asserted.
//!
//! Owned by plan 1-05.
