//! Passphrase generation (Crockford base32 from the OS CSPRNG, generated by
//! default) and the 12-character floor applied to a user-supplied one, with the
//! offline-attack cost explained rather than asserted.
//!
//! **Why the floor is higher than a login form's.** A login form is rate
//! limited; this is not. The encrypted bundle lives in a git repository, so an
//! attacker who obtains it can guess offline, forever, on hardware they own. At
//! roughly 10^5 Argon2id guesses per second — the rate the locked parameters
//! buy — a century of grinding covers about 2^55 candidates. Every human-chosen
//! password worth remembering is inside that. That is why [`generate`] is the
//! default path and a user-supplied password is the exception, and why
//! [`OFFLINE_ATTACK_NOTE`] explains the risk in words rather than printing a
//! rule.
//!
//! **The floor and the KDF cost are one control, so [`check`] takes both.** That
//! "rate the locked parameters buy" is the whole derivation of the number 12,
//! and nothing used to hold the parameters to it: a bundle written at a lower
//! `--kdf-memory` bought a cheaper guess while the length rule stayed put. Two
//! halves close it — `crypto::MIN_KDF_MEMORY_KIB` refuses the absurd end
//! outright, and below the shipped memory cost the accepted length rises from
//! [`MIN_CHARS`] to [`RECOMMENDED_CHARS`]. Lowering the KDF therefore costs
//! password length rather than security.
//!
//! **That is a length rule, and length is only a proxy for entropy.** Say it
//! plainly, because three earlier drafts of these docs said "below the default
//! memory cost nothing short of a generated passphrase is accepted" and the code
//! never did that: [`check`] counts characters, [`generate`] emits exactly
//! [`RECOMMENDED_CHARS`] of them, and 20 typed characters are therefore
//! indistinguishable from 20 CSPRNG ones to every line in this file. The proxy
//! is honest at the bottom — a 6-character password is weak no matter who chose
//! it — and weak at the top, where `20` may mean 100 uniform bits or may mean a
//! remembered phrase worth 40.
//!
//! Carrying provenance out of [`generate`] would make the rule real and was
//! rejected: a generated passphrase kept in a password manager comes back
//! through the same stdin as anything else, so the type would refuse exactly the
//! users it exists to bless. The honest control is that [`generate`] is the
//! default path and [`OFFLINE_ATTACK_NOTE`] explains why.
//!
//! **Only three ways a password enters the process:** a reader ([`read_line`],
//! for a pipe or stdin), a mode-0600 file ([`read_from_file`]), and a TTY
//! prompt, whose *wording* belongs to whichever surface owns the terminal.
//! The one part of it that lives here is [`MARKER`] — the unterminated,
//! flushed `password: ` that makes a blocking read look like a question rather
//! than a hang — because [`read_line`] is the one door all four asks go
//! through and a marker at the door cannot be forgotten by the fifth caller.
//! There is no function taking a password from a
//! command-line argument or from the environment: argv is world-readable
//! through `/proc`, environment values are inherited by children and land in
//! crash dumps, and the project already forbids credentials in process
//! arguments. `no_password_input_path_reads_the_process_environment` enforces
//! that.
//!
//! Every password returned from this module lives in `Zeroizing`. No error here
//! interpolates one — a failure says what could not be read, never what was
//! read.
//!
//! Owned by plan 1-05.

use std::io::BufRead;
use std::path::Path;

use zeroize::Zeroizing;

use crate::error::{AppError, Result};
use crate::sync::crypto::KdfParams;

/// Crockford base32: the digits and uppercase letters minus `I`, `L`, `O` and
/// `U`, so nothing in a generated passphrase can be misread off a screen or
/// mis-typed from a note.
const ALPHABET: &[u8; 32] = b"0123456789ABCDEFGHJKMNPQRSTVWXYZ";

/// Characters in a generated passphrase. 20 × 5 bits = exactly 100 bits, which
/// is past the point where the offline attack in the module docs matters.
const GENERATED_CHARS: usize = 20;

/// Below this a supplied password is refused outright.
pub const MIN_CHARS: usize = 12;

/// Below this a supplied password is accepted with a warning.
pub const RECOMMENDED_CHARS: usize = 20;

/// Printed by every surface that sets a password, before it is set.
pub const NO_RECOVERY: &str = "\
There is no recovery. No reset link, no support address, no escrow copy, no \
back door. If you lose this password the bundle is permanently unreadable and \
its contents are gone — by design, because that is the only way a hosted \
backup can be safe to hand to a server you do not control.";

/// Printed alongside [`NO_RECOVERY`] whenever the user supplies their own
/// password instead of taking a generated one (CRYPTO-06 requires the risk
/// explained in plain language, not merely enforced).
pub const OFFLINE_ATTACK_NOTE: &str = "\
Your password is the only thing protecting this bundle. Anyone who gets a copy \
of the repository — a service that hosts it, someone who forks it, anyone who \
later gets into your account — can sit at their own machine and guess at it as \
long as they like. There is nothing on the other end to lock them out after \
three tries or to notice they are trying at all. That is why the length floor \
exists, and why a generated passphrase is the recommended choice.";

/// The message on a refusal.
const TOO_SHORT: &str = "\
Too short — at least 12 characters are required. A short password is guessed \
offline in minutes; see the offline-attack note. Take the generated passphrase \
instead if you have somewhere safe to keep it.";

/// The message on a refusal under a lowered KDF cost.
const WEAKENED_KDF: &str = "\
Too short for a bundle at this key-derivation cost. Lowering the memory cost \
makes every offline guess cheaper, and the length rules are calculated against \
the full cost — so below it the minimum is 20 characters rather than 12. Length \
is all that can be checked, and it proves nothing on its own: take the generated \
passphrase, or put the memory cost back.";

/// The message on a warning.
const THIN: &str = "\
Accepted, but thin. Six random words from the EFF diceware list — chosen by \
dice or a generator, not by you — is about 77 bits and is the smallest thing \
worth typing here. A generated passphrase is stronger still.";

/// The verdict on a user-supplied password. Carries only fixed message text; it
/// never holds or echoes the password.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Strength {
    /// Below the hard floor. Do not proceed.
    Rejected(&'static str),
    /// Above the floor but below the recommendation. Proceed after showing the
    /// message.
    Weak(&'static str),
    /// At or above the recommendation.
    Strong,
}

/// Generate a passphrase: 20 Crockford base32 characters, exactly 100 bits,
/// straight from the OS CSPRNG. This is the recommended path; a user-supplied
/// password is the exception.
///
/// 13 bytes are drawn and the first 100 of those 104 uniform bits are consumed
/// five at a time, so every character is an unbiased draw from the 32-character
/// alphabet — no modulo bias, and no embedded wordlist to ship.
pub fn generate() -> Result<Zeroizing<String>> {
    let mut bytes = Zeroizing::new([0u8; 13]);
    getrandom::fill(&mut bytes[..])
        .map_err(|_| AppError::Other("the operating system random source is unavailable".into()))?;

    let mut out = Zeroizing::new(String::with_capacity(GENERATED_CHARS));
    for i in 0..GENERATED_CHARS {
        let bit = i * 5;
        let (byte, offset) = (bit / 8, bit % 8);
        let window = u16::from(bytes[byte]) << 8 | u16::from(bytes[byte + 1]);
        let index = ((window >> (11 - offset)) & 0x1f) as usize;
        out.push(ALPHABET[index] as char);
    }
    Ok(out)
}

/// Judge a user-supplied password by length, measured in **characters** rather
/// than bytes so a passphrase with non-ASCII is not flattered by its UTF-8
/// length — **at the KDF cost `k` the bundle will actually be written at**.
///
/// Length is a floor, not a score: no entropy estimator can tell a memorable
/// phrase from a leaked one, and pretending otherwise would hand the user a
/// green checkmark for `correcthorsebattery`. The real control is [`generate`].
///
/// `k` is not decoration. [`MIN_CHARS`] is arithmetic against the guess rate the
/// *shipped* parameters buy, so a bundle written at a lower `--kdf-memory` moves
/// that arithmetic without moving the rule — the two controls were calibrated
/// against each other and enforced apart. Below [`KdfParams::default`]'s memory
/// the trade has to be paid for on the other side: the accepted length rises
/// from [`MIN_CHARS`] to [`RECOMMENDED_CHARS`], so a user who lowers the cost
/// cannot also keep a short password.
///
/// **A longer password, not a provably stronger one.** 20 characters is what
/// [`generate`] emits, but this function sees only a string and cannot tell a
/// generated passphrase from a typed one of the same length — see the module
/// docs, and do not restate the rule as "only a generated passphrase is
/// accepted".
pub fn check(pw: &str, k: KdfParams) -> Strength {
    let n = pw.chars().count();
    if n >= RECOMMENDED_CHARS {
        return Strength::Strong;
    }
    if k.m_kib < KdfParams::default().m_kib {
        return Strength::Rejected(WEAKENED_KDF);
    }
    if n < MIN_CHARS {
        return Strength::Rejected(TOO_SHORT);
    }
    Strength::Weak(THIN)
}

/// The prompt marker, drawn immediately before an interactive read.
///
/// **No trailing newline, and it is flushed** — those two facts are the whole
/// fix. Without them the cursor rests at column 0 of a blank line and a user who
/// has just watched a silent Argon2id second and a half reads it as a hang
/// rather than a question. Short on purpose: the sentence explaining that the
/// password is echoed is already on the line above it.
pub const MARKER: &str = "password: ";

/// Read a password from a reader — a pipe, or stdin when the caller has already
/// decided this is not an interactive terminal.
///
/// **`marker` is not optional to supply, only to be `None`.** It is `Some` with
/// the stream the caller's own prompt text went to, and `None` for a pipe or a
/// file. Putting it here rather than at the four asks is what makes it
/// impossible for the fifth to forget: there is no way to read a sync password
/// without answering the question. The stream is the caller's because the two
/// surfaces disagree — `sync pull`'s prompt goes to stderr and `sync setup`'s
/// goes to stdout — and a prompt split across two streams is worse than none.
///
/// Write failures are **swallowed**: a closed prompt stream must not fail a
/// password read that is otherwise fine, exactly as in `push::progress`.
///
/// Only a single trailing newline (and the `\r` of a `\r\n` pair) is stripped.
/// Nothing else is trimmed: a password may legitimately begin or end with a
/// space, and silently eating it would make a correct password fail to open a
/// bundle it created.
pub fn read_line(
    mut r: impl BufRead,
    marker: Option<&mut dyn std::io::Write>,
) -> Result<Zeroizing<String>> {
    if let Some(out) = marker {
        let _ = write!(out, "{MARKER}");
        let _ = out.flush();
    }
    let mut line = Zeroizing::new(String::new());
    r.read_line(&mut line)
        .map_err(|e| AppError::Other(format!("could not read the password: {e}")))?;
    if line.ends_with('\n') {
        line.pop();
        if line.ends_with('\r') {
            line.pop();
        }
    }
    Ok(line)
}

/// Read a password from a file that only its owner can read.
///
/// The mode is checked on the *opened handle*, not the path, so the file that
/// was inspected is the file that is read. Any group or other bit is a refusal:
/// a password file another local user can read is not a password file.
pub fn read_from_file(path: &Path) -> Result<Zeroizing<String>> {
    let file = std::fs::File::open(path).map_err(|e| AppError::io_at(path, e))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::MetadataExt;
        let mode = file
            .metadata()
            .map_err(|e| AppError::io_at(path, e))?
            .mode();
        if mode & 0o077 != 0 {
            return Err(AppError::Other(format!(
                "the password file {} is group- or world-accessible (mode {:04o}); \
                 run `chmod 600` on it before using it",
                path.display(),
                mode & 0o7777
            )));
        }
    }
    // A file is never a prompt.
    read_line(std::io::BufReader::new(file), None)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_generated_passphrase_is_twenty_crockford_characters_and_never_repeats() {
        let a = generate().unwrap();
        let b = generate().unwrap();
        assert_eq!(a.chars().count(), 20);
        assert!(
            a.chars().all(|c| ALPHABET.contains(&(c as u8))),
            "every character must come from the Crockford alphabet"
        );
        assert_ne!(*a, *b, "two draws from the CSPRNG must differ");
    }

    #[test]
    fn every_alphabet_character_is_reachable() {
        // Guards the five-bit slicing: an off-by-one in the shift would make
        // whole regions of the alphabet unreachable and quietly cost entropy.
        let mut seen = std::collections::HashSet::new();
        for _ in 0..200 {
            seen.extend(generate().unwrap().chars());
        }
        assert_eq!(seen.len(), 32, "all 32 characters must be reachable");
    }

    /// The shipped cost, which is what [`MIN_CHARS`] is calibrated against.
    const FULL: KdfParams = KdfParams {
        m_kib: 1_048_576,
        t: 3,
        p: 1,
    };

    #[test]
    fn a_password_below_the_floor_is_refused() {
        assert!(matches!(check("short", FULL), Strength::Rejected(_)));
        assert!(matches!(check("elevenchars", FULL), Strength::Rejected(_)));
        let Strength::Rejected(msg) = check("short", FULL) else {
            panic!("must be rejected");
        };
        assert!(msg.contains("12 characters"));
    }

    #[test]
    fn a_password_between_the_floor_and_the_recommendation_warns_about_diceware() {
        let Strength::Weak(msg) = check("fifteenchars123", FULL) else {
            panic!("15 characters must warn, not reject or pass");
        };
        assert!(msg.contains("diceware"));
        assert!(msg.contains("Six random words"));
    }

    #[test]
    fn twenty_characters_is_strong() {
        assert_eq!(check("twenty-characters-!!", FULL), Strength::Strong);
        // And the recommended path clears the gate it recommends.
        assert_eq!(check(&generate().unwrap(), FULL), Strength::Strong);
    }

    /// The coupling. `MIN_CHARS` is arithmetic against the guess rate the
    /// shipped parameters buy, so a bundle written cheaper has to pay for it in
    /// password *length* instead: the floor rises from 12 to 20.
    ///
    /// Pinned as a length rule on purpose. Four documents used to call it an
    /// entropy rule — "refused unless it is of generated strength" — which this
    /// code has never enforced and cannot: `GENERATED_CHARS ==
    /// RECOMMENDED_CHARS`, so 20 typed characters and 20 CSPRNG characters are
    /// one input to `check`. The last assertion here is the one that keeps the
    /// documents honest.
    #[test]
    fn a_lowered_kdf_cost_raises_the_accepted_length_from_twelve_to_twenty() {
        let lowered = KdfParams {
            m_kib: FULL.m_kib / 2,
            ..FULL
        };

        // Everything the full cost merely warns about is refused outright.
        for pw in ["fifteenchars123", "nineteen-chars-abcd"] {
            let Strength::Rejected(msg) = check(pw, lowered) else {
                panic!("{pw:?} must be refused below the shipped KDF cost");
            };
            assert!(msg.contains("20 characters rather than 12"));
            assert!(matches!(check(pw, FULL), Strength::Weak(_)));
        }

        // …and a generated passphrase still clears it, at any cost.
        assert_eq!(check(&generate().unwrap(), lowered), Strength::Strong);
        assert_eq!(
            check(
                &generate().unwrap(),
                KdfParams {
                    m_kib: 8,
                    t: 1,
                    p: 1
                }
            ),
            Strength::Strong
        );

        // The gate is the *default* memory, not a re-typed literal: raising the
        // shipped parameters must raise this with them.
        assert_eq!(FULL, KdfParams::default());

        // What the rule actually is. A typed 20-character password clears the
        // lowered cost exactly as a generated one does — the function counts
        // characters and `generate` emits 20 of them, so nothing in the string
        // says where it came from. Any document claiming otherwise describes
        // behaviour that is not here.
        assert_eq!(GENERATED_CHARS, RECOMMENDED_CHARS);
        assert_eq!(check("twenty-characters-!!", lowered), Strength::Strong);
    }

    #[test]
    fn length_is_measured_in_characters_not_utf8_bytes() {
        // 12 characters, 24 bytes: judged by what the user typed.
        let twelve = "ααααααααββββ";
        assert_eq!(twelve.chars().count(), 12);
        assert!(twelve.len() > 12);
        assert!(matches!(check(twelve, FULL), Strength::Weak(_)));
    }

    #[test]
    fn reading_a_line_strips_one_newline_and_nothing_else() {
        let pw = read_line(&b"trailing space \n"[..], None).unwrap();
        assert_eq!(*pw, "trailing space ");

        let crlf = read_line(&b"windows\r\n"[..], None).unwrap();
        assert_eq!(*crlf, "windows");

        let bare = read_line(&b"no newline at all"[..], None).unwrap();
        assert_eq!(*bare, "no newline at all");

        // Only the *first* line is the password; a second line is not merged in.
        let first = read_line(&b"first\nsecond\n"[..], None).unwrap();
        assert_eq!(*first, "first");
    }

    /// The reported defect: two `println!`s and then a blocking read left the
    /// cursor at column 0 of a blank line, and a user who had just watched a
    /// silent Argon2id second and a half read it as a hang.
    ///
    /// Driven through the writer seam — no pty — which is also what proves the
    /// marker is **flushed**: a `Vec<u8>` holds what was written, and the
    /// `write!` that never reached it would be the bug this exists to fix.
    #[test]
    fn an_interactive_read_draws_an_unterminated_marker_and_a_piped_one_draws_nothing() {
        let mut shown: Vec<u8> = Vec::new();
        let pw = read_line(&b"a private passphrase\n"[..], Some(&mut shown)).unwrap();
        assert_eq!(*pw, "a private passphrase");

        let marker = String::from_utf8(shown).unwrap();
        assert_eq!(marker, MARKER);
        assert!(
            !marker.ends_with('\n'),
            "the cursor must rest after the marker, not below it: {marker:?}"
        );
        assert!(!marker.contains('\x1b'), "never styled: {marker:?}");
        assert!(!marker.is_empty(), "a prompt that draws nothing is the bug");

        // Piped: `None`, and so byte-identical to what this command has always
        // emitted — which is what the macOS menu bar and the Node contract
        // suites parse. There is no stream here for a marker to reach.
        assert_eq!(*read_line(&b"piped\n"[..], None).unwrap(), "piped");
    }

    /// The marker is drawn **before** the read and nothing is drawn after it,
    /// so no path here can echo, log or style what was typed.
    #[test]
    fn nothing_after_the_marker_carries_the_password() {
        let secret = "correct horse battery staple";
        let mut shown: Vec<u8> = Vec::new();
        let pw = read_line(format!("{secret}\n").as_bytes(), Some(&mut shown)).unwrap();
        assert_eq!(*pw, secret);
        let written = String::from_utf8(shown).unwrap();
        assert_eq!(written, MARKER, "{written:?}");
        assert!(!written.contains("horse"), "{written:?}");
    }

    #[cfg(unix)]
    #[test]
    fn a_group_readable_password_file_is_refused_and_a_private_one_is_read() {
        use std::os::unix::fs::PermissionsExt;

        let dir = tempfile::TempDir::new().unwrap();
        let path = dir.path().join("password");
        std::fs::write(&path, b"a private passphrase\n").unwrap();

        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o644)).unwrap();
        let err = read_from_file(&path)
            .expect_err("a group- or world-readable password file must be refused")
            .to_string();
        assert!(err.contains("chmod 600"));
        assert!(
            !err.contains("a private passphrase"),
            "an error must never echo the password"
        );

        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600)).unwrap();
        assert_eq!(*read_from_file(&path).unwrap(), "a private passphrase");
    }

    #[test]
    fn the_no_recovery_text_states_the_consequence_without_hedging() {
        assert!(NO_RECOVERY.contains("no recovery") || NO_RECOVERY.contains("No recovery"));
        assert!(NO_RECOVERY.contains("permanently unreadable"));
        for hedge in ["may be", "might", "possibly", "usually", "in most cases"] {
            assert!(
                !NO_RECOVERY.to_lowercase().contains(hedge),
                "the no-recovery text must not hedge with {hedge:?}"
            );
        }
    }

    #[test]
    fn the_offline_attack_note_explains_the_risk_in_plain_language() {
        // Plain language means no jargon: the point is that a user who
        // understands "this can be attacked forever, offline" picks better than
        // one told "minimum 12 characters".
        assert!(OFFLINE_ATTACK_NOTE.contains("guess at it as long as they like"));
        assert!(OFFLINE_ATTACK_NOTE.contains("lock them out"));
        for jargon in ["entropy", "Argon2", "KDF", "bits of", "brute-force"] {
            assert!(
                !OFFLINE_ATTACK_NOTE.contains(jargon),
                "the offline-attack note must avoid the jargon {jargon:?}"
            );
        }
    }

    /// **The whole of `src/sync/`, walked — not a list of files.**
    ///
    /// argv and the environment are readable by any local user through /proc,
    /// environment values are inherited by children, and both land in crash
    /// dumps. The three sanctioned input paths are a reader, a mode-0600 file,
    /// and a TTY prompt owned by the calling surface.
    ///
    /// This used to iterate three hand-written names. Phase 3's F-8 found the
    /// list had not been extended when `github/setup.rs` grew a passphrase
    /// surface, and the remediation *added setup.rs to the list*. Phase 4 then
    /// added `push/rekey.rs` — the file T-4-47 (critical) is about, and the one
    /// that holds two live passwords — and the list was not extended again;
    /// the audit proved it by putting `std::env::var("SYNC_PW")` in `rekey.rs`
    /// and watching this test pass. A guard that enumerates what to check fails
    /// open on everything written after it, so this one enumerates the
    /// *exemptions* instead and scans everything else.
    #[test]
    fn no_password_input_path_reads_the_process_environment() {
        // The one exemption, and it is not a password path: `token::resolve`
        // reads the GitHub *token* from the environment on purpose, which is a
        // documented and deliberately different rule (a token is revocable; a
        // sync password is not). Anything else added to this list needs the same
        // kind of justification written next to it.
        const EXEMPT: &str = "src/sync/github/token.rs";

        let mut scanned = 0usize;
        let mut skipped = 0usize;
        for path in crate::sync::guard::rs_files_in("src/sync") {
            if path.ends_with(std::path::Path::new(EXEMPT).file_name().unwrap())
                && path.to_string_lossy().contains("github")
            {
                skipped += 1;
                continue;
            }
            scanned += 1;
            let source = std::fs::read_to_string(&path).expect("readable module");
            // Prose may discuss the rule freely, and test modules may name the
            // needles; only shipped code is scanned. `production_code` drops
            // both — comments first, so a doc comment naming `#[cfg(test)]`
            // cannot truncate the region this loop sees, which is how five
            // production functions in `github/pairing.rs` sat outside this
            // guard while it reported green on a real violation (F-4).
            let production = crate::sync::guard::production_code(&source);
            for line in production.lines() {
                let trimmed = line.trim_start();
                for needle in ["std::env", "env::var", "var_os", "clap", "Arg::new"] {
                    assert!(
                        !trimmed.contains(needle),
                        "{} reads {needle} — only a reader, a mode-0600 file, and a \
                         TTY prompt are sanctioned password input paths",
                        path.display()
                    );
                }
            }
        }
        assert_eq!(skipped, 1, "the token reader is exempted exactly once");
        assert!(scanned >= 20, "only {scanned} files walked under src/sync");
    }
}
